SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I, ITEM_TREE AS T
WHERE I.ITEM_ID = T.ITEM_ID
    AND I.ITEM_ID NOT IN (
        SELECT DISTINCT(PARENT_ITEM_ID)
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NOT NULL
    )
ORDER BY I.ITEM_ID DESC;