WITH CAR AS (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
HISTORY AS(
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DURING_DATE,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE)>=90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)>=30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)>=7  THEN '7일 이상'
            ELSE '해당 없음'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
DISCOUNT AS(
    SELECT DURATION_TYPE, SUBSTRING_INDEX(DISCOUNT_RATE, '%',1) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)
SELECT HISTORY_ID,
    CASE
        WHEN HISTORY.DURATION_TYPE = '해당 없음' THEN HISTORY.DURING_DATE * CAR.DAILY_FEE
        ELSE (100-DISCOUNT.DISCOUNT_RATE)*CAR.DAILY_FEE/100*HISTORY.DURING_DATE
    END AS FEE
FROM CAR JOIN HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID, DISCOUNT
WHERE HISTORY.DURATION_TYPE = DISCOUNT.DURATION_TYPE OR (HISTORY.DURATION_TYPE='해당 없음' AND DISCOUNT.DURATION_TYPE='7일 이상')
ORDER BY FEE DESC, HISTORY_ID DESC;
