SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, M.MAX_SIZE-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E, (
    SELECT MAX(SIZE_OF_COLONY) as MAX_SIZE, SUBSTRING(DIFFERENTIATION_DATE, 1, 4) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS M
WHERE SUBSTRING(E.DIFFERENTIATION_DATE, 1, 4) = M.YEAR
ORDER BY YEAR, YEAR_DEV;