WITH MAX_FISH AS(
    SELECT MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
)
SELECT I.ID, N.FISH_NAME, M.MAX_LENGTH AS LENGTH
FROM MAX_FISH AS M, FISH_INFO AS I, FISH_NAME_INFO AS N
WHERE I.FISH_TYPE = N.FISH_TYPE AND M.FISH_TYPE = I.FISH_TYPE AND M.MAX_LENGTH = I.LENGTH
ORDER BY ID;